export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';
export const APPLY_FILTER_BY_NAME = 'APPLY_FILTER_BY_NAME';
export const APPLY_FILTER_BY_DATE = 'APPLY_FILTER_BY_DATE';
export const APPLY_FILTER_BY_CATEGORY = 'APPLY_FILTER_BY_CATEGORY';
